### PR TITLE
Basic user-service logic with neo4j was created

### LINKED ISSUE #1: Create user-service basic logic with Neo4j

### PR DESCRIPTION
**Pull request by vpetrovaa**
## PR-Codex overview
This PR adds Neo4j database integration, validation, exception handling, DTO mapping, and date formatting to the Twitter application. 

### Detailed summary
- Added Neo4j database integration with UserRepository and UserService
- Added validation for UserDto fields
- Added ResourceAlreadyExistsException and ResourceDoesNotExistException for error handling
- Added ApiControllerAdvice for exception handling
- Added UserMapper for DTO mapping
- Added date formatting with DateFormatConfig
- Upgraded Spring Boot version to 3.1.0
- Added dependencies for lombok, mapstruct, and validation

> The following files were skipped due to too many changes: `src/main/java/com/solvd/twitter/service/impl/UserServiceImpl.java`, `src/main/java/com/solvd/twitter/web/controller/UserController.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by vpetrovaa** [comment]
@h1alexbel, I have some issues.
So, I had method to update my user:
1. I get user from db to update
2. Set him fields I need
3. And then call save method and return the user.
And the problem is that after calling save method from repository all the relationships of updated user were removed.
I debugged it and in first step when I called findById method everything was good and I got all my followers and followings(relationships). But exactly after calling save method I faced with this problem

**Comment by vpetrovaa** [comment]
@h1alexbel My solution was to create query in repository:
@Query("MATCH (u:User {id: :#{#user.id}}) SET u.name = :#{#user.name}, " +
            "u.surname = :#{#user.surname}, u.dateOfBirth = :#{#user.dateOfBirth} RETURN u")
    User update(@Param("user") User user);
and in service only call this method
So, is it a good idea? 
With it all my relationships persist and I have no problems whit them or updating

**Comment by vpetrovaa** [comment]
@h1alexbel Also this question is connected with fields to update. I send as parameter of this method whole user, but only three fields can be updated (password and email can't). Should I change it or it is connected more to ui?

**Review by h1alexbel — APPROVED** [review]

**Comment by h1alexbel** [comment]
@vpetrovaa I don't know too, but your solution looks good for now

**Pull request merged**
